[package]
name = "astrolabe"
version = "0.0.0"
edition = "2021"
description = "Date and time library for Rust"
authors = ["GiyoMoon"]
license = "MIT OR Apache-2.0"
keywords = ["date", "time"]
categories = ["date-and-time"]

[dependencies]
