[package]
name = "astrolabe"
version = "0.0.1"
edition = "2021"
description = "Date and time library for Rust. Aims to be feature rich and easy-to-use."
homepage = "https://github.com/giyomoon/astrolabe"
documentation = "https://docs.rs/astrolabe/"
repository = "https://github.com/giyomoon/astrolabe"
readme = "README.md"
authors = ["GiyoMoon"]
license = "MIT OR Apache-2.0"
keywords = ["date", "time"]
categories = ["date-and-time"]
include = [
    "src/**",
    "Cargo.toml",
    "README.md",
    "LICENSE-APACHE",
    "LICENSE-MIT",
]

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[dependencies]
fancy-regex = { version = "0.10.0", default-features = false, features = ["unicode"], optional = true }
once_cell = { version = "1.13.0", default-features = false, features = ["std"], optional = true }

[features]
format = ["fancy-regex", "once_cell"]
