name: audit

on:
  schedule:
    - cron: '0 0 * * 1,4'
  push:
    paths:
      - 'Cargo.toml'
      - '.github/workflows/audit.yml'
  pull_request:
    paths:
      - 'Cargo.toml'
      - '.github/workflows/audit.yml'
  workflow_dispatch:

jobs:
  audit:
    uses: giyomoon/workflows/.github/workflows/rust-audit.yml@main
    with:
      rust-version: nightly
